---
- name: "Configure {{ _broker.name }} broker.xml"
  template:
    src: "{{ artemis_templates.broker }}"
    dest: "{{ _broker.path }}/{{ _broker.name }}/etc/broker.xml"
  notify: "restart broker"

- name: "Configure {{ _broker.name }} bootstrap.xml"
  template:
    src: "{{ artemis_templates.bootstrap }}"
    dest: "{{ _broker.path }}/{{ _broker.name }}/etc/bootstrap.xml"
  notify: "restart broker"

- name: "Ensure ARTEMIS_HOME is correct in artemis.profile"
  lineinfile:
    dest: "{{ _broker.path }}/{{ _broker.name }}/etc/artemis.profile"
    regexp: "^ARTEMIS_HOME"
    line: "ARTEMIS_HOME='{{ _broker.artemis_home }}'"

- name: "Configure {{ _broker.name }} logging.properties"
  template:
    src: "{{ artemis_templates.logging }}"
    dest: "{{ _broker.path }}/{{ _broker.name }}/etc/logging.properties"
  notify: "restart broker"

- name: "Configure {{ _broker.name }} jolokia-access.xml"
  template:
    src: "{{ artemis_templates.jolokia_access }}"
    dest: "{{ _broker.path }}/{{ _broker.name }}/etc/jolokia-access.xml"
  notify: "restart broker"
